"""add column indice_active

Revision ID: 95ba6e9d8c85
Revises: aa0565d0cafe
Create Date: 2026-04-05 23:09:08.059569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ba6e9d8c85'
down_revision = 'aa0565d0cafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indice_active', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('indice_active')

    # ### end Alembic commands ###
