"""add column indice (Enigme)

Revision ID: aa0565d0cafe
Revises: f3cfad5c8254
Create Date: 2026-04-05 22:52:43.052015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0565d0cafe'
down_revision = 'f3cfad5c8254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enigmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enigmes', schema=None) as batch_op:
        batch_op.drop_column('indice')

    # ### end Alembic commands ###
