"""first migrate

Revision ID: f2feef696308
Revises: 
Create Date: 2026-05-13 18:37:26.670345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2feef696308'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('manches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('video_fin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('enigmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manche', sa.Integer(), nullable=False),
    sa.Column('enigme', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('indice', sa.Text(), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['manche'], ['manches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manche', 'enigme', name='uq_manche_enigme')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enigme_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('indice_active', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['enigme_id'], ['enigmes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'enigme_id', name='uq_user_enigme')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_table('progress')
    op.drop_table('enigmes')
    op.drop_table('users')
    op.drop_table('manches')
    op.drop_table('config')
    # ### end Alembic commands ###
